### ISSUE TITLE
[Teamserver-Client--Bug]: Modules are not loaded - "whoami", "arp", "listdns", etc.

### ISSUE THREAD

**Issue by dmcxblue** [HavocFramework/Havoc#253]
### What happened?

A bug happened!
Modules are not loaded when running "make" on the Client side

![image](https://user-images.githubusercontent.com/41899653/214879742-61918571-5274-4c70-ac0e-b2dd769ca684.png)

Also an error is given when you log onto the teamserver

![image](https://user-images.githubusercontent.com/41899653/214880155-df458bc5-9db9-4033-8fd8-1f8660f5bf62.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
./Havoc   
[10:00:06] [info] Havoc Framework [Version: 0.4.1] [CodeName: The Fool]
[10:00:06] [info] Successful created database
[10:00:19] [error] Couldn't check if DemonClass is ready
[10:00:19] [error] Couldn't check if AgentClass is ready
[10:00:19] [error] Couldn't check if Event class is ready
SystemError: type havoc.Event has the Py_TPFLAGS_HAVE_GC flag but has no traverse function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 579, in module_from_spec
  File "<frozen importlib._bootstrap>", line 533, in _init_module_attrs
SystemError: <function ModuleSpec.parent at 0x7f6185b4e160> returned a result with an exception set
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: cannot import name 'Demon' from 'havoc' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Demon' from 'havoc' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Demon' from 'havoc' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Demon' from 'havoc' (unknown location)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Demon' from 'havoc' (unknown location)
[10:00:20] [info] Started "Agent Listener - HTTP/s" listener
[10:00:20] [info] Started "Pivot - Smb" listener
[10:06:22] [info] Havoc Application status: 0
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by ag-michael** [comment]
Hi @dmcxblue , I'm also seeing this issue with the latest pull from main.

**Comment by activeshadow** [comment]
@dmcxblue this is likely due to the fact that Kali Rolling is now using Python v3.11. Even if you have Python v3.10 installed alongside v3.11, `cmake` will end up pulling in v3.11 because of the `${PYTHON_LIBRARIES}` cmake finder. The CMakeLists.txt file also hard-references v3.10 via `/usr/include/python3.10`.

At any rate, a temporary fix is to replace `${PYTHON_LIBRARIES}` with `/usr/lib/x86_64-linux-gnu/libpython3.10.so` in CMakeLists.txt. A better fix would be to figure out why the client scripting engine doesn't work with versions newer than 3.10.

Also want to thank @glattercj for helping to figure this out.

**Comment by SecT0uch** [comment]
The error is due to this change in python 3.11:The [PyType_Ready()](https://docs.python.org/3/c-api/type.html#c.PyType_Ready) function now raises an error if a type is defined with the [Py_TPFLAGS_HAVE_GC](https://docs.python.org/3/c-api/typeobj.html#Py_TPFLAGS_HAVE_GC) flag set but has no traverse function ([PyTypeObject.tp_traverse](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_traverse)). (Contributed by Victor Stinner in [bpo-44263](https://bugs.python.org/issue?@action=redirect&bpo=44263).)
